name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run
      run: |
        pipenv run python main.py
    - name: Check for changes
      id: check_changes
      run: |
        git diff-index --quiet HEAD || exit 1
    - name: Get current date
      if: steps.check_changes.outputs.result == 'success'
      id: get_date
      run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
    - name: Create branch and commit
      if: steps.check_changes.outputs.result == 'success'
      env:
        CURRENT_DATE: ${{ steps.get_date.outputs.date }}
      run: |
        git checkout -b "wiki-data-$CURRENT_DATE"
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Update wiki data"
    - name: Push changes
      if: steps.check_changes.outputs.result == 'success'
      uses: ad-m/github-push-action@master
      with:
        branch: wiki-data-${{ steps.get_date.outputs.date }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Pull Request
      if: steps.check_changes.outputs.result == 'success'
      uses: peter-evans/create-pull-request@v6
      with:
        branch: wiki-data-${{ steps.get_date.outputs.date }}
        title: "Automated PR: Update wiki data"
        body: |
          This pull request was automatically generated by a GitHub Actions workflow.
        token: ${{ secrets.GITHUB_TOKEN }}
